### ISSUE TITLE
#10 민성 - 투표 완성하면, 그 부분 리액트로 바꾸기

### ISSUE THREAD

**Issue by leesungbin** [arkss/uoscat#10]
이렇게 하면 새로고침 안하게 할 수 있을 것 같아욤
쓰면 편할 것 같은 놈 :  django-react-template
https://github.com/Frojd/django-react-templatetags

& 쓸 패키지
axios
: form post action -> axios
즉, 뷰에서는 사용자가 행동하는대로 보여주고, 요청은 axios로 다 보내서 처리할 것

**Comment by arkss** [comment]
오... 이거 지금봄... ㄱㅅ...
