### ISSUE TITLE
#성빈 글쓰기, 투표, 댓글에 유저 권한 부여하기 (google login)

### ISSUE THREAD

**Issue by arkss** [arkss/uoscat#16]

**Comment by leesungbin** [comment]
* User 모델 구성 ( social login 된 거)
* Vote, Choice, Comment 와 User 연결 (ForeignKey 부여)
* User authenticate
1) Vote 종료
2) Comment Edit, Delete 권한
3) User당 Vote에 Choice 1개씩 선택
